services:
  glasspack:
    build: .
    image: glasspack-back
    container_name: glasspack
    depends_on:
      - postgres_db
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/glasspack
    env_file:
      - .env
    networks:
      - dbnet

  postgres_db: 
    image: postgres:17
    container_name: data_base
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - dbnet

  web-server:
    image: nginx:stable
    container_name: mynginx
    networks:
      - dbnet
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/var/www/glasspack/static
      - ./media:/var/www/glasspack/media
    depends_on:
      - glasspack

volumes:
  db-data:

networks:
  dbnet:
    driver: bridge